In [6]:
x <- rnorm(10)
y <- rnorm(10)
summary(lm(y~x))


Call:
lm(formula = y ~ x)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.58568 -0.27474 -0.00841  0.56613  1.48025 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)  -0.7084     0.3014  -2.350   0.0466 *
x             0.1047     0.3973   0.263   0.7989  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.9323 on 8 degrees of freedom
Multiple R-squared:  0.008602,	Adjusted R-squared:  -0.1153 
F-statistic: 0.06941 on 1 and 8 DF,  p-value: 0.7989


In [ ]:
library("")

In [27]:
# help("*")

In [16]:
ls.str(pat="x")

x :  num [1:10] -0.257 -1.304 0.945 -0.773 1.202 ...

In [17]:
rm(x,y)

In [43]:
help.search("bs")

In [28]:
# help("bs", try.all.packages = TRUE)

In [30]:
# help.search("tree", rebuild=TRUE) 

In [33]:
# apropos("help")

In [34]:
log(2)

[1] 0.6931472

In [39]:
x <- rnorm(10)
# boxplot(x)

In [38]:
# help(boxplot)

In [44]:
help.search("lr")

In [51]:
length(dim(as.matrix(1:10)))

[1] 2

In [1]:
# ? matrix

In [66]:
mdat <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE)

In [68]:
dim(mdat)

[1] 2 3

In [69]:
getwd()

[1] "/home/zjmwqx/RNotebookCode"

In [89]:
t <- read.csv("data.dat", header=FALSE, sep=" ")

In [92]:
mydata <- scan("data.dat", what = list("", 0, 0))

In [104]:
z <- c(1,2,3,4)

In [106]:
rep(1,30)

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [107]:
sequence(4:5)

[1] 1 2 3 4 1 2 3 4 5

In [113]:
# expand.grid(a=c(60,80), b=c(100,300))

In [122]:
qnorm(0.025)

[1] -1.959964

In [123]:
1 - pchisq(3.84, 1)

[1] 0.05004352

In [124]:
numeric()

numeric(0)

In [127]:
factor(1:3)

[1] 1 2 3
Levels: 1 2 3

In [160]:
# need set levels when there is label not present in data
ff <-factor(1:3, levels=2:5, labels=c("A","B","C","D"))

In [164]:
x <- 1:15
dim(x) <- c(5,3)

In [165]:
x

[,1] [,2] [,3]
[1,]    1    6   11
[2,]    2    7   12
[3,]    3    8   13
[4,]    4    9   14
[5,]    5   10   15

In [168]:
x <- 1:4; n <-10; M <- c(10, 35); y <- 2:4

In [169]:
data.frame(x, n)

x  n
1 1 10
2 2 10
3 3 10
4 4 10

In [171]:
data.frame(x, M)

x  M
1 1 10
2 2 35
3 3 10
4 4 35

In [176]:
L1<-list(A=x,b=y)

In [180]:
ts(1:10, start=1959)

Time Series:
Start = 1959 
End = 1968 
Frequency = 1 
 [1]  1  2  3  4  5  6  7  8  9 10

In [206]:
ts(matrix(rpois(36, 5), 12, 3), start=c(1961, 1), frequency=12)

Series 1 Series 2 Series 3
Jan 1961        7        7        1
Feb 1961       11        6        4
Mar 1961        5        6        4
Apr 1961        2        3        4
May 1961        6       10        7
Jun 1961        3        2        6
Jul 1961        3        7        5
Aug 1961        5        5        8
Sep 1961        4        3        1
Oct 1961        0        7        3
Nov 1961        4        4        4
Dec 1961       11        7        7

In [207]:
ts(1:47, frequency = 4, start = c(1959, 2))

     Qtr1 Qtr2 Qtr3 Qtr4
1959         1    2    3
1960    4    5    6    7
1961    8    9   10   11
1962   12   13   14   15
1963   16   17   18   19
1964   20   21   22   23
1965   24   25   26   27
1966   28   29   30   31
1967   32   33   34   35
1968   36   37   38   39
1969   40   41   42   43
1970   44   45   46   47

In [208]:
x = 3; y = 2.5; z = 1

In [209]:
exp1 = expression(x / (y + exp(z)))

In [211]:
eval(exp1)

[1] 0.5749019

In [212]:
D(exp1, "x")

1/(y + exp(z))

In [213]:
fac = factor(c(1:10))

In [217]:
fac2 = factor(c("Male", "Female"))

In [219]:
as.numeric(fac2)

[1] 2 1

In [215]:
as.numeric(fac)

[1]  1  2  3  4  5  6  7  8  9 10

In [221]:
15 / 11

[1] 1.363636

In [225]:
0 < x & x < 1

[1] FALSE

In [226]:
all.equal(0.9, 1-0.1)

[1] TRUE

In [227]:
0.9 == (1.1 - 0.2)

[1] FALSE

In [229]:
0.9 == (1.0 - 0.1)

[1] TRUE

In [228]:
1.1 - 0.2

[1] 0.9

In [231]:
all.equal(0.9, 1.1-0.2, tolerance = 1e-16)

[1] "Mean relative difference: 1.233581e-16"

In [3]:
x <- matrix(1:6, 2, 3)

In [4]:
x[,3] <- 21:22

In [5]:
x[,3]

[1] 21 22

In [8]:
x <- rpois(40, lambda = 5)

In [7]:
x[x %% 2 == 0]

[1]  2  4 22

In [6]:
x[, 3, drop=FALSE]

[,1]
[1,]   21
[2,]   22

In [44]:
x<-list(1:3, 2,3)

In [17]:
x[[1]]

[1] 1 2 3

In [20]:
x[2:3]

[[1]]
[1] 2

[[2]]
[1] 3

In [22]:
names(x)

NULL

In [45]:
names(x) <- c("a", "b", "c")

In [25]:
x <- matrix(1:4, 2)

In [29]:
rownames(x) <- c("a", "b")
colnames(x) <- c("c", "d")
x

c d
a 1 3
b 2 4

In [32]:
A <- array(1:8, dim = c(2, 2, 2))

In [35]:
dimnames(A) <- list(c("a", "b"), c("c", "d"), c("e", "f"))

In [37]:
print(A)

, , e

  c d
a 1 3
b 2 4

, , f

  c d
a 5 7
b 6 8



In [40]:
A[,,"e"]

c d
a 1 3
b 2 4

In [50]:
x[[1]] ;x$a

[1] 1 2 3

[1] 1 2 3

In [55]:
X = matrix(1:8, nrow =2, ncol=4)

In [62]:
data.entry(X)  #will modify the content of matrix

In [64]:
de(X) #will not modify data, only display on the screen

In [77]:
m1 <- matrix(1, nrow=2, ncol=2)
m2 <- matrix(2, nrow=2, ncol=2)

In [71]:
rbind(m1, m2) %*% cbind(m1, m2)

[,1] [,2] [,3] [,4]
[1,]    2    2    4    4
[2,]    2    2    4    4
[3,]    4    4    8    8
[4,]    4    4    8    8

In [72]:
t(m1)

[,1] [,2]
[1,]    1    1
[2,]    1    1

In [78]:
diag(m1) ; diag(m1) <- 10;diag(m1)

[1] 1 1

[1] 10 10

In [80]:
diag(3); diag(1:3)

[,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

[,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

In [83]:
# ? solve qr eigen svd